# Generated by Django 3.2.7 on 2021-09-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20210909_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Email',
            field=models.EmailField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='confirm_password',
            field=models.IntegerField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.IntegerField(max_length=8, null=True),
        ),
    ]
