# Generated by Django 3.2.7 on 2021-09-12 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20210909_1740'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
