# Generated by Django 3.2.7 on 2021-09-14 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_delete_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
