# Generated by Django 3.2.7 on 2021-09-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0004_alter_book_book_img'),
        ('students', '0007_auto_20210917_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='books',
        ),
        migrations.AddField(
            model_name='profile',
            name='books',
            field=models.ManyToManyField(to='admins.Book'),
        ),
    ]
