# Generated by Django 3.2.7 on 2021-09-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_details',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
