# Generated by Django 3.2.7 on 2021-09-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0004_alter_book_book_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='borrowed_or',
            field=models.BooleanField(default=False),
        ),
    ]
